#!/bin/bash

# Interpreter needs to be Bash because I'm using Arrays

UUIDGEN=uuidgen

tpl=$1
dataFile=$2

files=()
count=0

for f in `\ls -1 "$tpl"/*yml`; do
	files[$count]=`basename "$f"`
	count=$((count + 1))	
done


IFS="	"
cat $dataFile | while read -a field; do
	for f in ${files[@]}; do
		u1=`$UUIDGEN`

		target=$f
		target=${target/_SLUG_/${field[0]}}
		
		sed -e "s|_SLUG_|${field[0]}|g; s|_NAME_|${field[1]}|g; s|_UUID_|$u1|g;" < "$tpl/$f" > "$target"
	done
done
