punctuation:
  double_quotes: 1
  quotes: 1
  backtick: 1
  comma: 1
  period: 2
  hyphen: 1
  underscore: 1
  colon: 1
  semicolon: 1
  pipe: 1
  left_curly: 1
  left_square: 1
  right_curly: 1
  right_square: 1
  plus: 1
  equal: 1
  asterisk: 1
  ampersand: 1
  percent: 1
  caret: 1
  dollar: 1
  hash: 1
  at: 1
  exclamation: 1
  tilde: 1
  left_parenthesis: 1
  right_parenthesis: 1
  question_mark: 1
  less_than: 1
  greater_than: 1
  slash: 1
  back_slash: 1
verbose: true
separator: '-'
max_length: 255
max_component_length: 100
transliterate: true
reduce_ascii: false
ignore_words: 'a, an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with'
case: true
update_action: 2
_core:
  default_config_hash: x3zd5G959ntrLWnPqsPRjCqmznMo4F9Z3fmvE89Hcak
